#!/usr/bin/env python3
"""Generate legitimate company, career, Academy and entity-authority pages."""

from __future__ import annotations

import html
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BASE = "https://www.theclinixai.com"

PAGES = [
    ("company-profile", "TheClinixAI Company Profile", "An AI and pharmacovigilance company building governed safety-intelligence software, scientific resources, consulting capability and practical professional development.", "The company behind the Nexus safety-intelligence platform.", "TheClinixAI is being built around one operating belief: patient-safety technology must understand the scientific decisions it is expected to support.", [("What we build", "Connected pharmacovigilance workspaces spanning literature, intake, cases, review, quality, submissions, signals and aggregate safety."), ("How we work", "Product decisions begin with PV workflow, regulatory context, evidence traceability and accountable human review."), ("Why it matters", "Safety teams need technology that reduces fragmentation without hiding the judgement behind a decision.")]),
    ("clinixai-india", "TheClinixAI India", "ClinixAI India brings pharmacovigilance operations, healthcare expertise and enterprise AI engineering together to build globally relevant patient-safety technology.", "Built in India for global pharmacovigilance operations.", "India contributes deep pharmacovigilance delivery capability, healthcare talent and technology expertise to global medicine safety. ClinixAI is building from that foundation while designing for regional requirements and multinational operating models.", [("Global context", "Workflows are designed to accommodate product, country, language, partner and regional regulatory differences."), ("Indian capability", "The operating model draws on Indian pharmacovigilance, clinical, regulatory and software experience."), ("Patient-safety purpose", "Geography informs execution; scientific integrity and traceability remain universal expectations.")]),
    ("leadership", "TheClinixAI Leadership", "Meet the multidisciplinary leadership contributors shaping ClinixAI across patient safety, operations, submissions, product strategy, customer delivery and community development.", "Different disciplines. One patient-safety purpose.", "ClinixAI is shaped by professionals who understand different parts of the safety lifecycle. The leadership model brings medical engagement, business operations, PV delivery, regulatory submissions, clinical product strategy and platform vision into the same decision process.", [("Scientific and product direction", "Madhu Padishala and Adithya contribute platform vision, clinical innovation and product strategy."), ("Operations and customer delivery", "Surya Teja and Althaf contribute dependable execution, operational governance and customer strategy."), ("Regulatory and community perspective", "Harsha and Wany contribute submission discipline, professional engagement and healthcare community development.")]),
    ("patient-safety-mission", "ClinixAI Patient-Safety Mission", "ClinixAI exists to strengthen patient-safety decisions through traceable evidence, accountable human judgement and governed pharmacovigilance technology.", "Built for patient safety. Engineered to trace every decision.", "Patient safety is not a marketing layer added after product development. It is the criterion used to challenge workflow design, automation scope, evidence handling and accountability across the Nexus platform.", [("Evidence before automation", "The system should preserve what was received, what was inferred, what was reviewed and what was finally decided."), ("Human accountability", "AI may organise and prioritise information; authorised professionals remain responsible for scientific and regulatory outcomes."), ("Continuous learning", "Quality findings, overrides and operational evidence should improve controlled processes rather than disappear into isolated trackers.")]),
    ("responsible-ai-governance", "Responsible AI Governance at TheClinixAI", "How ClinixAI governs intended use, knowledge context, model outputs, human oversight, validation, change control and evidence for AI-assisted pharmacovigilance.", "AI assistance must remain visible, bounded and accountable.", "A persuasive model response is not proof of a safe pharmacovigilance decision. ClinixAI separates evidence, governed knowledge, deterministic rules, model output, reviewer action and final disposition so each layer can be evaluated.", [("Defined intended use", "Every AI capability should have a controlled purpose, known limitations and an accountable user."), ("Governed context", "Effective procedures, regulations, product data and tenant rules must shape the decision environment."), ("Validated change", "Models, prompts, rules and knowledge require versioning, testing, approval and monitored performance.")]),
    ("pharmacovigilance-technology", "Pharmacovigilance Technology at TheClinixAI", "Explore ClinixAI's approach to interoperable pharmacovigilance technology, governed knowledge, workflow intelligence and evidence-led automation.", "Technology should follow the safety decision—not force the decision to follow the software.", "ClinixAI treats pharmacovigilance as a connected information lifecycle. Architecture is organised around source provenance, workflow states, accountable roles, governed knowledge, decision evidence and downstream regulatory consequences.", [("Connected workspaces", "Literature, intake, cases, review, QC, submissions and cumulative safety activities share evidence."), ("Knowledge-aware workflows", "The system retrieves effective context rather than hardcoding every rule inside one opaque agent."), ("Enterprise controls", "Role-based access, audit evidence, versioning and controlled configuration support dependable operations.")]),
    ("research-scientific-programme", "ClinixAI Research and Scientific Programme", "The ClinixAI research programme publishes practical pharmacovigilance guidance, architecture papers and evidence-led perspectives for safety professionals.", "Research written to be used—not merely downloaded.", "ClinixAI research connects scientific standards, operational reality and technology design. Publications are intended to help professionals understand what a workflow must control and why that control matters.", [("Scientific guidance", "Mother and specialist articles explain PV decisions from literature through quality and regulatory action."), ("Architecture papers", "Research papers describe governed AI, compliant system design and traceable safety intelligence."), ("Evidence programme", "Future validation publications will report intended use, datasets, performance, limitations and operational observations.")]),
    ("careers", "Careers at TheClinixAI", "Explore careers, internships and professional opportunities at ClinixAI across pharmacovigilance, healthcare technology, quality, research and customer delivery.", "Build the future of safety intelligence.", "ClinixAI is developing at the intersection of pharmacovigilance and enterprise technology. Opportunities require curiosity, ownership and the discipline to defend decisions with evidence.", [("Pharmacovigilance", "Opportunities may span literature, cases, quality, submissions, signals, aggregates and safety operations."), ("Technology", "Engineering work focuses on governed knowledge, workflow, data integrity, explainable AI and product reliability."), ("Business and delivery", "Customer strategy, implementation, research and professional education connect the platform to real operating needs.")]),
    ("pharmacovigilance-careers", "Pharmacovigilance Careers at TheClinixAI", "Learn what ClinixAI expects from pharmacovigilance professionals across case processing, literature, medical review, quality, submissions, signals and aggregate reporting.", "A PV professional must be able to defend the decision—not only complete the field.", "Pharmacovigilance careers require more than terminology familiarity. Professionals must understand evidence, chronology, minimum criteria, seriousness, expectedness, causality, follow-up, reportability and the quality consequences of each decision.", [("Operational discipline", "Work must be timely, attributable and consistent with effective procedures."), ("Scientific reasoning", "The reviewer should distinguish explicit evidence from assumptions and explain the rationale."), ("Technology fluency", "Modern professionals should understand how automation assists work, where it fails and how human oversight is documented.")]),
    ("pharmacovigilance-internship-programme", "Pharmacovigilance Internship Programme", "A structured ClinixAI Academy internship programme focused on practical internal pharmacovigilance projects, guided learning, measurable participation and professional decision-making.", "Do not collect another certificate. Build evidence that you can perform the work.", "The ClinixAI Academy internship is designed as a structured learning and internal-project engagement—not regular salaried employment and not client casework. Participants practise how PV decisions are made, documented, reviewed and defended.", [("Structured foundation", "Participants work through safety concepts, controlled workflows and professional terminology."), ("Internal projects", "Exercises are designed by ClinixAI to simulate realistic PV decisions without using confidential client data."), ("Documented engagement", "Attendance, assignments, diligence and project participation support an experience record subject to programme policy.")]),
    ("graduate-pharmacovigilance-programme", "Graduate Pharmacovigilance Programme", "A practical pharmacovigilance development pathway for healthcare graduates seeking structured exposure to safety operations, scientific judgement and workplace expectations.", "A degree establishes potential. Practice develops professional judgement.", "Healthcare graduates often know the definitions but have not yet applied them under a controlled workflow. This programme focuses on the transition from remembering PV concepts to evaluating evidence and documenting a defensible decision.", [("Decision practice", "Participants evaluate patient, reporter, product, event, seriousness and follow-up scenarios."), ("Workflow understanding", "Learning follows the safety lifecycle rather than disconnected classroom topics."), ("Professional readiness", "Feedback focuses on accuracy, rationale, communication, ownership and controlled execution.")]),
    ("academy-corporate-training", "Corporate Pharmacovigilance and AI Training", "ClinixAI Academy provides corporate pharmacovigilance and responsible-AI training designed around operating models, controlled workflows and adoption readiness.", "Prepare safety teams to use AI without weakening professional accountability.", "Corporate training should not stop at tool demonstrations. Teams need a shared understanding of intended use, evidence verification, escalation, override, data handling, validation and change governance.", [("Role-based curriculum", "Content can be structured for operations, medical review, quality, leadership and technology stakeholders."), ("Workflow application", "Training uses controlled PV scenarios instead of generic AI examples."), ("Adoption evidence", "Knowledge checks, exercises and action plans help organisations evaluate readiness and follow-through.")]),
    ("partner-with-clinixai", "Partner with TheClinixAI", "Partner with ClinixAI across pharmacovigilance technology, scientific research, healthcare education, implementation, validation and patient-safety innovation.", "The strongest safety systems are built with the people who must operate them.", "ClinixAI welcomes serious collaboration with pharmaceutical companies, CROs, hospitals, healthcare institutions, researchers, educators and technology partners where responsibilities and patient-safety purpose are clear.", [("Product collaboration", "Explore workflow validation, implementation, integration and controlled pilot opportunities."), ("Scientific collaboration", "Contribute to research, evaluation datasets, operational evidence and responsible-AI dialogue."), ("Capability development", "Develop role-relevant PV and technology learning with institutions and corporate teams.")]),
    ("media-newsroom", "TheClinixAI Media and Newsroom", "Official ClinixAI company information, research updates, product announcements, media resources and expert pharmacovigilance commentary.", "A reliable source for ClinixAI facts, research and announcements.", "The newsroom provides a controlled reference for journalists, partners, researchers and industry professionals. Product status, research findings and company information should be sourced from current ClinixAI materials rather than inferred from third-party listings.", [("Company updates", "Announcements covering platform development, partnerships, Academy programmes and operational milestones."), ("Research releases", "New scientific guides, architecture papers and future validation evidence."), ("Expert commentary", "Context on pharmacovigilance operations, governed AI, patient safety and regulatory technology.")]),
    ("quality-compliance", "Quality and Compliance at TheClinixAI", "ClinixAI's quality and compliance approach covers controlled development, traceable requirements, validation evidence, security, access control and accountable change.", "Inspection readiness begins in ordinary development and operational decisions.", "Quality cannot be added immediately before customer validation. ClinixAI is building controls around requirements, risk, testing, defects, approvals, release evidence and change so the product's behaviour can be explained.", [("Traceable requirements", "Business, PV, regulatory and technical requirements should connect to implementation and verification evidence."), ("Risk-based assurance", "Controls and testing depth should reflect patient-safety, compliance and data-integrity impact."), ("Controlled change", "Configuration, code, models, prompts and knowledge require versioning, approval and release evidence.")]),
]


def esc(value: str) -> str:
    return html.escape(value, quote=True)


def render(slug: str, title: str, description: str, hook: str, intro: str, pillars: list[tuple[str, str]]) -> str:
    url = f"{BASE}/{slug}"
    cards = "".join(f"<article><span>0{i}</span><h2>{esc(name)}</h2><p>{esc(copy)}</p></article>" for i, (name, copy) in enumerate(pillars, 1))
    faq = [
        (f"What is {title}?", description),
        ("How does this connect to the ClinixAI Nexus platform?", "The page describes the company, capability or programme context supporting ClinixAI's governed pharmacovigilance platform and professional ecosystem."),
        ("How can an organisation or professional engage with ClinixAI?", "Use the discovery or contact route to provide the relevant organisation, workflow, programme or collaboration context."),
    ]
    faq_html = "".join(f"<details><summary>{esc(q)}</summary><p>{esc(a)}</p></details>" for q, a in faq)
    schema = {
        "@context": "https://schema.org",
        "@graph": [
            {"@type": "Organization", "@id": f"{BASE}/#organization", "name": "TheClinixAI", "alternateName": ["ClinixAI", "The Clinix AI"], "url": f"{BASE}/", "logo": {"@type": "ImageObject", "url": f"{BASE}/icon-512.png"}},
            {"@type": "WebPage", "@id": f"{url}#webpage", "url": url, "name": title, "description": description, "about": {"@id": f"{BASE}/#organization"}},
            {"@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": a}} for q, a in faq]},
        ],
    }
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(title)} | TheClinixAI</title><meta name="description" content="{esc(description)}"><meta name="robots" content="index,follow,max-image-preview:large">
<link rel="canonical" href="{url}"><meta property="og:title" content="{esc(title)} | TheClinixAI"><meta property="og:description" content="{esc(description)}"><meta property="og:url" content="{url}"><meta property="og:type" content="website"><meta property="og:image" content="{BASE}/icon-512.png"><meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="/icon-32.png"><link rel="stylesheet" href="/style.css?v=20260723h"><script type="application/ld+json">{json.dumps(schema, ensure_ascii=False, separators=(",", ":"))}</script></head>
<body class="entity-page"><a class="skip" href="#main">Skip to content</a><div id="site-header"></div><main id="main">
<header class="entity-hero"><div class="shell"><p>THECLINIXAI · COMPANY &amp; CAPABILITY</p><h1>{esc(hook)}</h1><div><strong>{esc(title)}</strong><span>{esc(description)}</span></div></div></header>
<section class="entity-intro"><div class="shell"><p>{esc(intro)}</p></div></section>
<section class="entity-pillars"><div class="shell">{cards}</div></section>
<section class="entity-belief"><div class="shell"><p>WHAT REMAINS CONSTANT</p><h2>Patient safety, scientific integrity, human accountability and enterprise trust.</h2><a href="/end-to-end-pharmacovigilance-nexus-platform">Explore the Nexus platform →</a></div></section>
<section class="entity-faq"><div class="shell"><p>USEFUL CONTEXT</p><h2>Frequently asked questions</h2>{faq_html}</div></section>
<section class="entity-cta"><div class="shell"><div><p>START A RELEVANT CONVERSATION</p><h2>Tell us the problem, programme or collaboration you are evaluating.</h2></div><a class="button button-secondary" href="/contact">Contact TheClinixAI</a></div></section>
</main><div id="site-footer"></div><script src="/site.js"></script></body></html>'''


def main() -> None:
    for page in PAGES:
        (ROOT / f"{page[0]}.html").write_text(render(*page), encoding="utf-8")
    print(f"Generated {len(PAGES)} company, career and Academy authority pages.")


if __name__ == "__main__":
    main()
