#!/usr/bin/env python3
"""Generate hospital pharmacovigilance and medication-safety authority pages."""

from __future__ import annotations

import html
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BASE = "https://www.theclinixai.com"
WHO_MED = "https://www.who.int/initiatives/medication-without-harm"
WHO_INCIDENT = "https://www.who.int/publications/i/item/9789240010338"
WHO_PV = "https://www.who.int/teams/regulation-prequalification/regulation-and-safety/pharmacovigilance"
PVPI = "https://www.ipc.gov.in/mandates/pvpi/adr-monitoring-centers.html"

PAGES = [
    ("hospital-pharmacovigilance-programme", "Hospital Pharmacovigilance Programme", "Build a governed hospital pharmacovigilance programme for ADR recognition, collection, assessment, reporting, learning and patient-safety oversight.", "A medicine-safety programme must work where treatment decisions happen.", "Hospitals observe suspected adverse reactions, medication errors, treatment failures and special situations at the point of care. A dependable programme makes reporting simple, preserves clinical evidence and turns individual reports into organisational learning.", [("Governance", "Define leadership, committee oversight, reporting routes, responsibilities and escalation."), ("Clinical reporting", "Enable doctors, nurses, pharmacists and patients to report relevant medicine-safety information."), ("Learning", "Review trends, contributing factors, outcomes and actions without reducing the programme to report counts.")]),
    ("adr-reporting-system-hospitals", "ADR Reporting System for Hospitals", "A hospital ADR reporting system for accessible clinical reporting, minimum information, follow-up, assessment, submission and feedback.", "If reporting is difficult, safety information remains inside the clinical encounter.", "An ADR reporting system should reduce reporting friction while collecting enough evidence for meaningful follow-up. It must distinguish initial notification from formal assessment and provide feedback so clinical teams understand that reporting produces action.", [("Accessible intake", "Offer clear reporting routes appropriate to hospital roles and patient access."), ("Clinical evidence", "Capture patient, medicine, reaction, timing, investigations, outcome and reporter context."), ("Controlled follow-up", "Prioritise missing information and preserve all communication and assessment evidence.")]),
    ("hospital-medication-safety-software", "Hospital Medication-Safety Software", "Hospital medication-safety software for incident capture, medication-error learning, high-risk medicines, trends, investigations, CAPA and committee oversight.", "Medication safety improves when incidents become structured learning—not isolated blame.", "Weak systems and human factors can affect prescribing, transcribing, dispensing, administration and monitoring. Technology should help hospitals recognise patterns, investigate contributing conditions and verify that corrective actions reduce recurrence.", [("Medication journey", "Capture where the event occurred across prescribing, dispensing, administration and monitoring."), ("Risk intelligence", "Identify high-alert medicines, repeated error types, care settings and vulnerable transitions."), ("Action governance", "Connect investigation, recommendations, ownership, CAPA and effectiveness evidence.")]),
    ("medication-error-reporting-hospitals", "Medication-Error Reporting in Hospitals", "Design a blame-aware medication-error reporting workflow covering near misses, harm events, contributing factors, investigation and learning.", "Near misses are safety evidence—not failed reports because harm did not occur.", "A mature hospital programme encourages reporting of errors and near misses, separates learning from unjust blame and evaluates the system conditions surrounding the event. Reporting data has limitations, but it can expose risks that would otherwise remain invisible.", [("Report", "Capture what happened, where, when, medicine, stage, outcome and immediate response."), ("Analyse", "Evaluate contributing workflow, communication, environment, technology and human factors."), ("Prevent", "Implement and verify practical actions rather than closing the record after documentation.")]),
    ("patient-safety-incident-reporting-system", "Patient-Safety Incident Reporting System", "A patient-safety incident reporting and learning system for structured capture, analysis, governance, feedback and prevention across hospital care.", "Reporting creates value only when the organisation learns from what was reported.", "Incident systems are not incidence-rate databases and should not be interpreted without understanding underreporting and selection. Their strength is structured learning: identifying hazards, contributing factors, repeated patterns and opportunities to reduce avoidable harm.", [("Minimum information", "Collect sufficient structured and narrative context without making reporting impractical."), ("Learning model", "Classify harm, event type, contributing factors, detection and recovery."), ("Feedback loop", "Communicate actions and learning so reporters can see the purpose of participation.")]),
    ("adverse-event-intake-healthcare-professionals", "Adverse-Event Intake from Healthcare Professionals", "Capture adverse-event information from healthcare professionals with source preservation, minimum-criteria support, clinical follow-up and controlled safety routing.", "The first clinical report should reach the right safety workflow without losing its original meaning.", "Healthcare professionals may report through hospitals, medical information, manufacturers, partners or national systems. Intake should preserve the reporter's words, clinical context and receipt information while enabling appropriate follow-up and downstream routing.", [("Preserve", "Retain original report content, attachments, timestamps and source identity controls."), ("Clarify", "Request clinically meaningful missing information without leading the reporter."), ("Route", "Direct information to hospital learning, pharmacovigilance or partner exchange as applicable.")]),
    ("hospital-drug-safety-committee", "Hospital Drug-Safety Committee", "Establish a hospital drug-safety committee with defined scope, evidence review, medication-safety oversight, ADR learning and accountable action tracking.", "A committee is effective only when its decisions change controlled practice.", "Drug-safety oversight benefits from multidisciplinary review across medicine, pharmacy, nursing, quality and administration. The committee should use reliable evidence, distinguish individual-case action from system learning and track decisions through verified completion.", [("Mandate", "Define scope, membership, quorum, escalation, confidentiality and decision rights."), ("Evidence review", "Evaluate ADRs, medication errors, trends, high-risk medicines and emerging concerns."), ("Accountable action", "Assign owners, due dates, evidence requirements and effectiveness review.")]),
    ("medication-safety-audit-capa-hospitals", "Medication-Safety Audit and CAPA for Hospitals", "Hospital medication-safety audits and CAPA covering risk-based scope, findings, root cause, corrective action and effectiveness verification.", "The purpose of an audit finding is not closure. It is controlled reduction of recurrence risk.", "Audits can evaluate medication governance, storage, prescribing, dispensing, administration, monitoring, incident reporting and learning. Findings should describe objective evidence and risk; CAPA should address causes rather than merely restating the observation.", [("Risk-based audit", "Prioritise high-risk medicines, processes, settings, transitions and previous failures."), ("Root-cause discipline", "Separate immediate containment, contributing factors and systemic causes."), ("Effectiveness", "Define evidence and monitoring periods capable of showing whether risk was reduced.")]),
    ("hospital-pharmacovigilance-training", "Pharmacovigilance Training for Hospital Staff", "Role-based hospital pharmacovigilance and medication-safety training for doctors, pharmacists, nurses, quality teams and administrators.", "Every hospital employee does not need the same PV lesson. Every relevant role needs to know what to recognise and what to do next.", "Training should match the decisions each role makes: recognising suspected reactions, documenting evidence, responding clinically, preserving source information, reporting promptly and participating in learning. Completion records alone do not demonstrate competence.", [("Role relevance", "Tailor examples and responsibilities to doctors, pharmacists, nurses, quality and leadership."), ("Scenario practice", "Use cases involving ADRs, medication errors, special situations and incomplete information."), ("Competency evidence", "Assess application, escalation and documentation rather than attendance alone.")]),
    ("hospital-mah-safety-data-exchange", "Hospital–MAH Safety-Data Exchange", "Govern safety-data exchange between hospitals and marketing authorisation holders with clear scope, contacts, timelines, privacy, follow-up and reconciliation.", "A safety report should not become untraceable because it crosses an organisational boundary.", "Hospitals and MAHs may need to exchange suspected adverse-reaction information while respecting applicable privacy, ethics, consent, contractual and regulatory requirements. Responsibilities and follow-up routes should be clear before urgent cases arise.", [("Defined scope", "Clarify products, report types, parties, contacts, evidence and permitted data exchange."), ("Controlled transfer", "Preserve source, date, case reference, acknowledgement and follow-up status."), ("Reconciliation", "Identify missing transfers, mismatched records, duplicates and outstanding information.")]),
]


def esc(value: str) -> str:
    return html.escape(value, quote=True)


def render(page: tuple) -> str:
    slug, title, description, hook, intro, pillars = page
    url = f"{BASE}/{slug}"
    references = f'<a href="{WHO_MED}" target="_blank" rel="noopener">WHO Medication Without Harm</a> · <a href="{WHO_INCIDENT}" target="_blank" rel="noopener">WHO incident reporting guidance</a> · <a href="{WHO_PV}" target="_blank" rel="noopener">WHO pharmacovigilance</a> · <a href="{PVPI}" target="_blank" rel="noopener">PvPI ADR Monitoring Centres</a>'
    cards = "".join(f"<article><span>0{i}</span><h2>{esc(name)}</h2><p>{esc(copy)}</p></article>" for i, (name, copy) in enumerate(pillars, 1))
    faq = [
        (f"What is {title}?", description),
        ("Does this replace national or hospital reporting requirements?", "No. Hospital processes must be configured to applicable law, national programmes, institutional policy and professional responsibilities."),
        ("Can ClinixAI support an existing hospital programme?", "The workflow can be evaluated against existing governance, forms, committees, reporting routes and technology before any implementation decision."),
    ]
    faq_html = "".join(f"<details><summary>{esc(q)}</summary><p>{esc(a)}</p></details>" for q, a in faq)
    schema = {"@context": "https://schema.org", "@graph": [{"@type": "Organization", "@id": f"{BASE}/#organization", "name": "TheClinixAI", "url": f"{BASE}/"}, {"@type": "Service", "name": title, "description": description, "provider": {"@id": f"{BASE}/#organization"}, "url": url}, {"@type": "FAQPage", "mainEntity": [{"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": a}} for q, a in faq]}]}
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)} | TheClinixAI</title><meta name="description" content="{esc(description)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="{url}"><meta property="og:title" content="{esc(title)} | TheClinixAI"><meta property="og:description" content="{esc(description)}"><meta property="og:url" content="{url}"><meta property="og:type" content="website"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/icon-32.png"><link rel="stylesheet" href="/style.css?v=20260723i"><script type="application/ld+json">{json.dumps(schema, ensure_ascii=False, separators=(",", ":"))}</script></head>
<body class="hospital-page"><a class="skip" href="#main">Skip to content</a><div id="site-header"></div><main id="main"><header class="hospital-hero"><div class="shell"><p>HOSPITAL PHARMACOVIGILANCE &amp; MEDICATION SAFETY</p><h1>{esc(hook)}</h1><span>{esc(description)}</span><a class="button button-primary" href="/contact">Discuss your hospital programme</a></div></header>
<section class="hospital-intro"><div class="shell"><h2>{esc(title)}</h2><p>{esc(intro)}</p></div></section><section class="hospital-pillars"><div class="shell">{cards}</div></section>
<section class="hospital-framework"><div class="shell"><div><p>CONTROL FRAMEWORK</p><h2>Recognise. Report. Review. Learn. Prevent.</h2></div><ol><li>Make reporting accessible to relevant staff and patients.</li><li>Preserve clinical evidence and protect information appropriately.</li><li>Apply accountable assessment and escalation.</li><li>Identify patterns without overstating incident-reporting data.</li><li>Track action and effectiveness through governance.</li></ol></div></section>
<section class="hospital-sources"><div class="shell"><p>AUTHORISED CONTEXT</p><h2>Designed around recognised patient-safety principles.</h2><p>Hospitals must apply applicable national requirements and institutional procedures. Useful authoritative context includes {references}.</p></div></section>
<section class="entity-faq"><div class="shell"><p>PROGRAMME QUESTIONS</p><h2>Frequently asked questions</h2>{faq_html}</div></section>
<section class="entity-cta"><div class="shell"><div><p>BUILD THE OPERATING MODEL</p><h2>Connect hospital reporting, medication safety and pharmacovigilance learning.</h2></div><a class="button button-secondary" href="/contact">Start a discovery discussion</a></div></section></main><div id="site-footer"></div><script src="/site.js"></script></body></html>'''


def main() -> None:
    for page in PAGES:
        (ROOT / f"{page[0]}.html").write_text(render(page), encoding="utf-8")
    print(f"Generated {len(PAGES)} hospital and medication-safety pages.")


if __name__ == "__main__":
    main()
