#!/usr/bin/env python3
from pathlib import Path
from bs4 import BeautifulSoup

INSIGHTS_DIR = Path(__file__).resolve().parent.parent / "insights"

ARTICLE = """
<p>A serious case lands late on a Friday. The reporter writes "severe liver injury," the lab values are scattered across two follow-up emails, the suspect medicine was stopped, and the patient improved. The case processor enters everything, codes the event, marks the case complete. Every mandatory field is populated. The submission clock is running.</p>
<p>The case isn't ready, though.</p>
<p>Look closer at the chronology and the abnormal liver tests actually started before the suspect medicine did. The narrative implies improvement after withdrawal, but the source never actually establishes a true dechallenge. Someone picked the seriousness criterion off the word "severe," with no evidence of hospitalization, disability, life-threatening status, or another medically important condition behind it. The source documents hold facts the structured fields never captured.</p>
<aside class="article-callout">This is where pharmacovigilance quality actually becomes visible: not when a system accepts the case, but when a trained reviewer catches what the system can't safely decide on its own.</aside>
<p>People often describe quality control and medical review as "final checks." I think that undersells them badly. Together, they're the control layer that turns processed safety data into a scientifically coherent, regulator-ready ICSR. QC protects fidelity, completeness, and procedural consistency. Medical review protects clinical meaning, medical reasoning, and whether the safety conclusions can actually be defended. Submission is what converts that governed case into a regulatory message.</p>
<p>Read this alongside the principles in <a href="https://www.ema.europa.eu/en/human-regulatory-overview/post-authorisation/pharmacovigilance-post-authorisation/good-pharmacovigilance-practices-gvp" rel="noopener noreferrer" target="_blank">EMA Good Pharmacovigilance Practices (GVP)</a>, particularly Module VI, and the harmonised standards from the <a href="https://www.ich.org/page/efficacy-guidelines" rel="noopener noreferrer" target="_blank">International Council for Harmonisation</a>. Regional rules, your own company procedures, and product-specific obligations still govern the actual operational decision.</p>
<h2 id="what-quality-actually-means-in-an-icsr">What quality actually means in an ICSR</h2>
<p>ICSR quality isn't the same thing as data-entry completeness. A case can be technically complete and still be scientifically wrong. It can sail through system validation while misrepresenting the source. It can have a polished narrative that quietly conceals an incorrect chronology. It can be medically plausible and still get submitted to the wrong authority, under the wrong classification, or outside the applicable timeline.</p>
<p>A defensible ICSR has to satisfy four connected things:</p>
<ul><li>Source fidelity — the case accurately reflects what was reported, without invention, distortion or silent loss of clinically relevant information.</li><li>Data integrity — structured fields, codes, dates, products, events and narratives are internally consistent, attributable and traceable.</li><li>Scientific coherence — the medical interpretation respects chronology, known pharmacology, alternative explanations, clinical course and the limits of available evidence.</li><li>Regulatory correctness — validity, seriousness, expectedness, reportability, destination and submission timing are determined under the applicable rules.</li></ul>
<p>QC and medical review contribute to these differently. Their responsibilities can overlap, but I'd never collapse their purposes into one job.</p>
<h2 id="quality-control-and-medical-review-are-not-the-same-decision">Quality control and medical review are not the same decision</h2>
<div class="article-table-wrap"><table><tr><th><strong>Control layer</strong></th><th><strong>Primary question</strong></th><th><strong>Typical focus</strong></th><th><strong>Required outcome</strong></th></tr><tr><td>Case processing</td><td>Was the source converted into structured safety data?</td><td>Receipt, intake, coding, data entry, narrative and follow-up</td><td>A complete processing draft</td></tr><tr><td>Quality control</td><td>Does the case accurately and consistently represent the source and procedure?</td><td>Source-to-field verification, coding, dates, chronology, consistency and compliance</td><td>A corrected, traceable case</td></tr><tr><td>Medical review</td><td>Are the clinical interpretation and safety assessments scientifically defensible?</td><td>Diagnosis, seriousness, causality, expectedness, alternatives and medical follow-up</td><td>A medically coherent case</td></tr><tr><td>Submission readiness</td><td>Can the governed case be transmitted correctly and on time?</td><td>Reportability, destination, E2B rules, gateway validation and acknowledgement</td><td>A regulator-accepted message</td></tr></table></div>
<p>Ask QC to make every medical judgment and procedural review turns inconsistent and reviewer-dependent. Use expensive medical review time to fix basic transcription errors and you're wasting clinical expertise on work that didn't need it. A mature PV operating model defines who owns which decision, sets clear escalation rules and evidence requirements, and still keeps the two functions talking to each other.</p>
<h2 id="the-correct-control-sequence">The correct control sequence</h2>
<ol><li>Safety information is received, assessed for validity and assigned a defensible awareness date.</li><li>The case processor enters and codes the available information without going beyond the source.</li><li>QC compares the processed case with the source and the applicable procedural requirements.</li><li>Medical review evaluates the clinical story and medical assessments, including uncertainties and alternative explanations.</li><li>Any material findings are corrected, documented and, where necessary, returned through a governed rework loop.</li><li>Reportability and submission readiness are confirmed for each applicable market and reporting pathway.</li><li>The E2B message is transmitted, the acknowledgement is evaluated and any technical or business rejection is resolved.</li></ol>
<p>This sequence can be configured differently from one organization to the next, especially for non-serious cases, high-volume consumer reports, or follow-ups. But accelerating or automating the workflow doesn't make the underlying control objectives optional.</p>
<h2 id="what-an-icsr-quality-control-review-must-examine">What an ICSR quality-control review must examine</h2>
<p>A solid QC review is risk-based, source-driven, and independent enough to matter. It's not a casual reread of the case. It's testing whether the processed record would survive another competent reviewer trying to reconstruct it from scratch.</p>
<h3 id="1-case-identity-receipt-and-audit-trail">1. Case identity, receipt and audit trail</h3>
<p>Confirm the case identifier, source type, initial and follow-up classification, receipt dates, awareness date, version history, and linkage to the originating communication. Day zero needs to be backed by evidence, not chosen because it's convenient for the workflow.</p>
<p>Every source item should be attributable and sit in the right chronological order. Email bodies, attachments, call records, literature documents, partner transmissions, and translations shouldn't turn into disconnected fragments. If you can't reconstruct what was known, when it was known, and what changed, the case isn't inspection-ready — full stop.</p>
<h3 id="2-validity-and-reporter-information">2. Validity and reporter information</h3>
<p>QC needs to confirm the minimum case criteria still hold once all follow-up information is in: an identifiable patient, an identifiable reporter, a suspect medicinal product, and a suspected adverse reaction or reportable safety circumstance, as the applicable framework defines it.</p>
<p>Identifiable doesn't mean full personal information has to be on file. It means there's enough there to support a real patient or reporter and to avoid an obvious duplicate. Contactability, qualification, country, and primary-source status should be represented exactly as the source actually supports.</p>
<h3 id="3-patient-medical-history-and-exposure">3. Patient, medical history and exposure</h3>
<p>Check age, sex, weight, pregnancy status, relevant history, indications, concomitant conditions, and risk factors against the source. Exposure dates, dose, route, frequency, formulation, batch information, and therapy action all need to line up with the reported chronology.</p>
<p>Unknown isn't the same as not applicable. An estimated date isn't the same as an exact date. A calculated age isn't the same as a reported age. These distinctions actually matter, because structured data can go on to support signal detection, aggregate analysis, and regulatory decisions long after this case is closed.</p>
<h3 id="4-product-and-event-coding">4. Product and event coding</h3>
<p>Code medical concepts using the current governed version of <a href="https://www.meddra.org/" rel="noopener noreferrer" target="_blank">MedDRA</a>, and code medicinal products against the organization's controlled product dictionary and the applicable <a href="https://who-umc.org/whodrug/whodrug-global/" rel="noopener noreferrer" target="_blank">WHO Drug Global resources</a>. Coding should represent the documented concept — it shouldn't manufacture a diagnosis from symptoms unless the source and coding conventions actually support it.</p>
<p>QC should check verbatim-to-code consistency, specificity, hierarchy, duplicate event coding, product role, indication coding, and version alignment. If a reporter writes "rash and facial swelling," coding just "rash" throws information away. Coding "anaphylaxis" might be reading too much into it. What's correct depends on the source, the follow-up, and medically governed coding practice — not a shortcut.</p>
<h3 id="5-seriousness-and-outcome-consistency">5. Seriousness and outcome consistency</h3>
<p>Seriousness criteria need documented facts or a medically justified assessment behind them. Severity describes intensity. Seriousness is a regulatory classification based on outcome or intervention criteria — they're not the same axis. A severe headache can be non-serious. A mild-looking event can still be serious if it leads to hospitalization or represents a medically important condition.</p>
<p>Event outcome, patient outcome, hospitalization dates, interventions, and seriousness criteria all need to agree across the structured fields and the narrative. QC's job is spotting the contradictions. Medical review's job is resolving the medically complex ones.</p>
<h3 id="6-narrative-reconstruction">6. Narrative reconstruction</h3>
<p>The narrative isn't a decorative summary. It's the human-readable reconstruction of the case. It should lay out source, patient context, exposure, event chronology, investigations, treatment, action taken, outcome, reporter assessment, company assessment, and relevant follow-up — without repeating itself or speculating.</p>
<p>A good narrative lets someone independent understand the case without hunting through every field. A defensible one also makes the uncertainty visible. If dates conflict, the narrative shouldn't quietly pick one and move on. If causality was never given, it shouldn't hint that the reporter assessed the event as related when they didn't.</p>
<h3 id="7-cross-field-and-source-to-case-consistency">7. Cross-field and source-to-case consistency</h3>
<p>The strongest QC findings usually turn up between fields, not within one: an event onset before exposure even started; a positive dechallenge marked while the medicine was still being taken; a "recovered" outcome sitting next to a follow-up describing persistent symptoms; an unlisted event marked expected; an autopsy report attached to a case where the patient outcome field still says "unknown."</p>
<aside class="article-callout">A field can be correct sitting on its own and still make the whole case wrong once you read it as part of the clinical story.</aside>
<h2 id="what-medical-review-must-determine">What medical review must determine</h2>
<p>Medical review picks up where mechanical consistency leaves off. The reviewer's job isn't to rubber-stamp selections the processor already made. It's to determine whether the case interpretation is clinically credible, appropriately cautious, and backed by the evidence that was actually available at the time.</p>
<h3 id="clinical-coherence-and-chronology">Clinical coherence and chronology</h3>
<p>Reconstruct the temporal relationship between exposure, event onset, dose changes, withdrawal, treatment, investigations, and recovery. Chronology doesn't prove causality on its own, but you can't responsibly assess causality without it.</p>
<p>The real question isn't just whether the event happened after the medicine was taken. It's whether the whole pattern — biological plausibility, latency, dechallenge, rechallenge, competing causes, background risk — actually supports or weakens a causal association.</p>
<h3 id="diagnosis-and-medical-concept-selection">Diagnosis and medical concept selection</h3>
<p>A diagnosis might be explicitly reported, medically confirmed, provisionally suspected, or inferred from a compatible pattern. Those are four different states, not interchangeable ones. A reviewer should preserve the source diagnosis while working out whether the symptoms, tests, and clinical course actually support how the case has been represented.</p>
<p>Medical review should also catch when something more significant is hiding in fragmented data: liver-test abnormalities that suggest possible drug-induced liver injury, mucosal involvement and blistering that suggest a severe cutaneous reaction, or hypotension and bronchospasm treated with adrenaline that point to a potentially serious hypersensitivity reaction. A reviewer can request follow-up or refine coding under governed conventions, but shouldn't turn a possibility into a stated fact.</p>
<h3 id="seriousness-and-medical-importance">Seriousness and medical importance</h3>
<p>Follow the applicable regulatory framework and controlled medical criteria for seriousness. Many organizations use the <a href="https://www.ema.europa.eu/en/human-regulatory-overview/post-authorisation/pharmacovigilance-post-authorisation/eudravigilance/important-medical-event-terms-list-version-281" rel="noopener noreferrer" target="_blank">EMA Important Medical Events terms list</a> as one input into that decision — it doesn't replace case-specific medical judgment.</p>
<p>A medically important event can be serious even without death, immediate life threat, hospitalization, disability, or congenital anomaly, if medical or surgical intervention was needed to prevent that outcome. And being on a reference list is not a substitute for actually reading the case.</p>
<h3 id="expectedness-and-reference-safety-information">Expectedness and reference safety information</h3>
<p>Assess expectedness against the correct, effective reference document for the product, market, and reporting context. The event term, nature, specificity, severity, and outcome described in the reference safety information all matter. A broadly related label concept doesn't automatically make every clinical presentation expected.</p>
<p>Listedness, expectedness, and reportability are connected but they're not identical in every context. Know which reference document controls this particular decision and which regional rules apply — using an outdated reference version can flip an expedited-reporting outcome without anyone noticing.</p>
<h3 id="causality-and-alternative-explanations">Causality and alternative explanations</h3>
<p>Causality isn't a confidence score you generate from chronology alone. Weigh temporal compatibility, pharmacological plausibility, known class effects, dose-response information, dechallenge, rechallenge, concomitant medicines, underlying disease, infection, procedures, and any other credible explanation.</p>
<p>Keep reporter causality and company causality distinguishable. A company can disagree with a reporter, but the reporter's assessment shouldn't be overwritten or buried. And the absence of an explicit reporter assessment shouldn't quietly turn into "not related" — that's a different statement entirely.</p>
<h3 id="follow-up-as-a-medical-decision">Follow-up as a medical decision</h3>
<p>Drive follow-up requests off information that could actually change validity, seriousness, causality, expectedness, outcome, case understanding, or regulatory action. A generic questionnaire blasted out to every reporter generates activity without improving the evidence.</p>
<ul><li>For hepatic events: baseline and serial laboratory values, competing causes, imaging, alcohol history, viral testing, action taken and recovery.</li><li>For pregnancy: exposure timing, gestational age, prenatal testing, pregnancy outcome and infant follow-up where applicable.</li><li>For death: date and cause of death, relationship to the event, autopsy information and relevant terminal clinical course.</li><li>For medication error or overdose: circumstances, actual exposure, clinical consequences, intervention and preventability information.</li><li>For lack of efficacy involving critical therapy: product use, adherence, storage, disease course and clinical consequences.</li></ul>
<h2 id="from-review-findings-to-governed-rework">From review findings to governed rework</h2>
<p>A finding only matters once it's classified, corrected, and prevented from happening again. Define critical, major, and minor findings based on potential impact — not on whatever the reviewer happens to feel strongly about that day.</p>
<div class="article-table-wrap"><table><tr><th><strong>Finding level</strong></th><th><strong>Potential impact</strong></th><th><strong>Examples</strong></th></tr><tr><td>Critical</td><td>May affect patient safety, validity, expedited reportability, submission destination or regulatory compliance</td><td>Missed serious event; wrong suspect product; unsupported invalidation; incorrect day zero</td></tr><tr><td>Major</td><td>Materially affects case accuracy or medical interpretation but may not change immediate reportability</td><td>Incorrect coding specificity; contradictory chronology; omitted clinically relevant test result</td></tr><tr><td>Minor</td><td>Limited effect on interpretation or compliance; still requires correction or coaching</td><td>Formatting inconsistency; non-material wording issue; minor metadata defect</td></tr></table></div>
<p>Rework needs to preserve the audit trail — the original entry, the reviewer's finding, the correction, who was responsible, and when it was completed should all be reconstructable later. Repeated findings should feed into training, procedure improvement, system controls, and risk-based sampling. They shouldn't just sit as isolated comments in a reviewer's notes.</p>
<h2 id="risk-based-qc-without-lowering-the-quality-standard">Risk-based QC without lowering the quality standard</h2>
<p>Not every case needs the same intensity of review, but every case needs a controlled standard behind it. A risk-based model uses case characteristics to set review depth while still protecting the high-risk decisions.</p>
<ul><li>Prioritise fatal, life-threatening, paediatric, pregnancy, abuse, medication-error, product-quality and other medically significant cases.</li><li>Increase review depth for new products, new indications, emerging safety issues and jurisdictions with complex reporting rules.</li><li>Use processor performance, error history and case complexity to inform sampling—without creating blind spots.</li><li>Retain mandatory review points for validity, seriousness, day zero, expectedness, reportability and submission destination.</li><li>Periodically test the sampling model against fully reviewed control sets to detect false assurance.</li></ul>
<p>A low QC sampling rate isn't an achievement on its own. It's only defensible when the measured performance, stable processes, effective controls, and evidence that critical errors aren't slipping through actually back it up.</p>
<h2 id="submission-readiness-the-final-case-level-gate">Submission readiness: the final case-level gate</h2>
<p>Electronic transmission needs more than a clinically sound case behind it. The message has to comply with the applicable <a href="https://www.ich.org/page/e2br3-individual-case-safety-report-icsr-specification-and-related-files" rel="noopener noreferrer" target="_blank">ICH E2B(R3) ICSR specification and related files</a> and the receiving authority's regional implementation rules. For the EU, check the <a href="https://www.ema.europa.eu/en/human-regulatory-overview/research-development/pharmacovigilance-research-development/eudravigilance/electronic-reporting-suspected-adverse-reactions" rel="noopener noreferrer" target="_blank">EMA EudraVigilance electronic reporting guidance</a>.</p>
<p>Before transmission, confirm:</p>
<ul><li>The case is valid under the applicable framework and the version is correctly classified as initial, follow-up, amendment or nullification.</li><li>Seriousness, expectedness and reportability are aligned with the product, territory and reporting context.</li><li>The correct sender, receiver, message type, case identifiers and worldwide unique case identifier are used.</li><li>Mandatory E2B elements and regional data rules are satisfied without populating unsupported information.</li><li>Submission destinations and timelines reflect licences, studies, partner agreements and local obligations.</li><li>Gateway acknowledgements are monitored, technical and business errors are evaluated, and rejected messages are corrected and retransmitted under controlled procedures.</li></ul>
<p>A transmitted case isn't necessarily a successfully submitted one. You haven't demonstrated regulatory compliance until you've confirmed the receiving system's acknowledgement and resolved whatever error or rejection was blocking acceptance.</p>
<h2 id="where-automation-and-ai-can-and-cannot-help">Where automation and AI can — and can't — help</h2>
<p>Automation is genuinely good at comparing dates, flagging missing fields, spotting contradictions, checking dictionary versions, validating E2B syntax, flagging duplicate narratives, and routing complex cases. AI can help with source summarization, chronology extraction, coding suggestions, narrative drafting, and surfacing potential medical-review questions.</p>
<p>But assistance isn't accountability. An AI system can produce a clinically fluent explanation that the source doesn't actually support. It might read a temporal sequence as causality, mix up severity and seriousness, or land on a diagnosis from incomplete symptoms. Fluency can make an error harder to catch, not easier.</p>
<aside class="article-callout">The safe design principle is simple: automate evidence retrieval and consistency checking aggressively; govern medical conclusions conservatively.</aside>
<p>Any automated control needs a defined context of use, validated performance, version governance, traceable inputs and outputs, exception handling, and a clear path to human escalation. False-negative risk deserves particular attention here — a system that silently misses a serious or reportable feature can do more operational harm than one that throws a visible false alert.</p>
<h2 id="inspection-ready-evidence-of-quality">Inspection-ready evidence of quality</h2>
<p>An inspection-ready PV system needs to demonstrate more than "cases got processed." It needs to show the pharmacovigilance system was governed under an effective quality system. <a href="https://www.ema.europa.eu/en/documents/scientific-guideline/guideline-good-pharmacovigilance-practices-module-i-pharmacovigilance-systems-their-quality-systems_en.pdf" rel="noopener noreferrer" target="_blank">EMA GVP Module I</a> sets the EU framework for pharmacovigilance systems and their quality systems, while <a href="https://www.ema.europa.eu/en/documents/regulatory-procedural-guideline/guideline-good-pharmacovigilance-practices-gvp-module-vi-collection-management-submission-reports-suspected-adverse-reactions-medicinal-products-rev-2_en.pdf" rel="noopener noreferrer" target="_blank">GVP Module VI</a> covers collection, management, and submission of suspected adverse-reaction reports.</p>
<p>Inspectors and auditors can reasonably expect you to reconstruct:</p>
<ul><li>Who processed, quality-checked, medically reviewed and approved the case—and when.</li><li>Which source documents and translations supported each material decision.</li><li>Which SOP, work instruction, coding convention, reference safety information and regulatory rule were effective.</li><li>What findings were raised, how they were corrected and whether the submission outcome changed.</li><li>How late cases, rejected messages, overrides and deviations were investigated.</li><li>How quality metrics led to corrective and preventive action, training or system improvement.</li></ul>
<h2 id="a-practical-icsr-qc-and-medical-review-checklist">A practical ICSR QC and medical-review checklist</h2>
<ul><li>Case receipt, awareness date and source chronology are traceable.</li><li>Minimum validity criteria are supported and correctly represented.</li><li>Patient, reporter, product, event and exposure data match the source.</li><li>Medical history, concomitant therapy and relevant investigations are complete to the extent available.</li><li>MedDRA and product coding accurately represent the documented information.</li><li>Seriousness is supported and not confused with severity.</li><li>Expectedness uses the correct effective reference safety information.</li><li>Reporter and company causality assessments are distinct and evidence-based.</li><li>Narrative, structured fields and source documents tell the same clinical story.</li><li>Follow-up questions are medically targeted and proportionate.</li><li>Reportability, destination, timeline and case version are correct.</li><li>E2B and regional validation rules are satisfied.</li><li>Acknowledgement monitoring and rejection handling are operational.</li><li>All review decisions, corrections and overrides are auditable.</li></ul>
<h2 id="the-case-at-the-beginning-what-disciplined-review-changes">The case at the beginning: what disciplined review changes</h2>
<p>Back to the liver case. A superficial workflow submits a serious, positive-dechallenge case because the database fields look complete. Disciplined QC catches that the event chronology doesn't match the source, and that "severe" was mistakenly treated as a seriousness criterion. Medical review then works out that the liver-test abnormalities predated exposure, the reported improvement can't actually establish a drug dechallenge, and the clinically relevant alternative explanations still need follow-up.</p>
<p>Review was never about downgrading the case. It's about representing it honestly.</p>
<p>That distinction protects the patient, the reporter, the company, and the integrity of the safety database. It also protects everything built on top of this case later — expedited reporting, aggregate analysis, signal detection, benefit–risk evaluation — from resting on distorted evidence.</p>
<aside class="article-callout">Patient safety isn't protected by moving cases faster through a workflow. It's protected by making sure every case carries the correct evidence, the correct interpretation, and the correct regulatory action.</aside>
<h2 id="frequently-asked-questions">Frequently asked questions</h2>
<h3 id="what-is-icsr-quality-control-in-pharmacovigilance">What is ICSR quality control in pharmacovigilance?</h3>
<p>ICSR QC is the structured verification that a processed case accurately represents its source, follows controlled procedures and remains complete, consistent, traceable and regulator-ready. It includes source-to-field comparison, coding checks, chronology review, narrative consistency and confirmation of critical regulatory data.</p>
<h3 id="is-medical-review-mandatory-for-every-icsr">Is medical review mandatory for every ICSR?</h3>
<p>The exact workflow depends on applicable regulations, company procedures, case type and risk model. However, medical accountability must be defined for assessments that require clinical judgement. High-risk and medically complex cases should not depend solely on administrative or automated review.</p>
<h3 id="can-the-same-person-perform-case-processing-and-qc">Can the same person perform case processing and QC?</h3>
<p>Organisational models vary, but independence should be sufficient to control confirmation bias and detect errors objectively. Where staffing requires combined responsibilities, compensating controls, clear role separation and documented oversight become important.</p>
<h3 id="what-is-the-difference-between-qc-and-medical-review">What is the difference between QC and medical review?</h3>
<p>QC primarily tests fidelity, completeness, consistency and procedural compliance. Medical review evaluates clinical coherence, diagnosis, seriousness, causality, expectedness, alternative explanations and medically meaningful follow-up. Both are connected, but neither replaces the other.</p>
<h3 id="does-passing-e2b-validation-mean-the-case-is-medically-correct">Does passing E2B validation mean the case is medically correct?</h3>
<p>No. E2B validation confirms that a message meets technical or business rules. A technically valid message can still contain incorrect chronology, coding, seriousness, causality or medical interpretation.</p>
<h3 id="can-ai-perform-icsr-quality-control">Can AI perform ICSR quality control?</h3>
<p>AI can support extraction, comparison, contradiction detection, coding suggestions and review prioritisation. It should operate within a validated context of use, with traceable evidence and human accountability for consequential medical and regulatory decisions.</p>
<h2 id="conclusion">Conclusion</h2>
<p>A reliable pharmacovigilance system doesn't treat QC and medical review as speed bumps sitting between processing and submission. They're how the organization proves that speed hasn't replaced accuracy, that completeness hasn't replaced meaning, and that automation hasn't replaced accountability.</p>
<p>The strongest case isn't the one with the most fields filled in. It's the one whose facts can be traced, whose uncertainties are visible, whose medical reasoning holds up, and whose regulatory action is correct.</p>
<p>That's the standard I hold every case to: evidence before inference, governance before automation, patient safety before workflow convenience.</p>
<h2 id="authoritative-references">Authoritative references</h2>
<ul><li><a href="https://www.ema.europa.eu/en/human-regulatory-overview/post-authorisation/pharmacovigilance-post-authorisation/good-pharmacovigilance-practices-gvp" rel="noopener noreferrer" target="_blank">EMA — Good Pharmacovigilance Practices overview</a></li><li><a href="https://www.ema.europa.eu/en/documents/scientific-guideline/guideline-good-pharmacovigilance-practices-module-i-pharmacovigilance-systems-their-quality-systems_en.pdf" rel="noopener noreferrer" target="_blank">EMA — GVP Module I: Pharmacovigilance systems and quality systems</a></li><li><a href="https://www.ema.europa.eu/en/documents/regulatory-procedural-guideline/guideline-good-pharmacovigilance-practices-gvp-module-vi-collection-management-submission-reports-suspected-adverse-reactions-medicinal-products-rev-2_en.pdf" rel="noopener noreferrer" target="_blank">EMA — GVP Module VI: Collection, management and submission of suspected adverse-reaction reports</a></li><li><a href="https://www.ich.org/page/efficacy-guidelines" rel="noopener noreferrer" target="_blank">ICH — Efficacy guidelines, including E2 pharmacovigilance guidance</a></li><li><a href="https://www.ich.org/page/e2br3-individual-case-safety-report-icsr-specification-and-related-files" rel="noopener noreferrer" target="_blank">ICH — E2B(R3) ICSR specification and related files</a></li><li><a href="https://www.ema.europa.eu/en/human-regulatory-overview/research-development/pharmacovigilance-research-development/eudravigilance/electronic-reporting-suspected-adverse-reactions" rel="noopener noreferrer" target="_blank">EMA — Electronic reporting of suspected adverse reactions</a></li><li><a href="https://www.meddra.org/" rel="noopener noreferrer" target="_blank">MedDRA — official terminology resources</a></li><li><a href="https://who-umc.org/whodrug/whodrug-global/" rel="noopener noreferrer" target="_blank">Uppsala Monitoring Centre — WHODrug Global</a></li></ul>
<aside class="article-disclaimer"><strong>Professional scope:</strong> This article provides scientific and operational pharmacovigilance guidance. Applicable legislation, current regional requirements, company procedures and product-specific obligations must be assessed before regulatory action.</aside>
"""


def main():
    path = INSIGHTS_DIR / "quality-control-medical-review-pharmacovigilance.html"
    html = path.read_text(encoding="utf-8")
    soup = BeautifulSoup(html, "html.parser")
    article = soup.select_one("article.article-content")
    new_soup = BeautifulSoup(ARTICLE, "html.parser")
    article.clear()
    for child in list(new_soup.children):
        article.append(child)
    path.write_text(str(soup), encoding="utf-8")
    print("OK: quality-control-medical-review-pharmacovigilance.html")


if __name__ == "__main__":
    main()
